<template>
  <!-- Generated by Pixelmator Pro 3.7.1 -->
  <svg
    width="1024"
    height="1024"
    viewBox="0 0 1201 1180"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      id="loaderPath"
      fill="none"
      stroke="currentColor"
      stroke-width="100"
      stroke-linecap="round"
      pathLength="1"
      d="M 1042.969482 506.289856 C 1042.969482 506.289856 777.620117 737.34668 442.927582 737.361938 C 323.659363 737.36731 209.375153 727.749146 163.693985 824.51416 C 136.892838 881.286255 153.683899 977.128906 234.217346 1014.399902 C 294.221649 1042.170044 384.579498 1026.131348 438.175293 964.057861 C 614.948792 759.322449 462.4646 359.610046 423.455261 156.060425 C 422.481628 150.979858 426.177399 149.878906 428.019684 154.712402 C 533.902222 432.522766 693.270264 740.656494 848.581482 863.299255 C 889.954041 895.969482 926.923889 910.411255 978.440491 899.228149 C 1034.363647 887.088562 1049.181152 829.293823 1049.181152 829.293823"
    />
  </svg>
</template>

<style scoped lang="sass">
  #loaderPath
    stroke-dasharray: 1
    stroke-dashoffset: 1
    animation: draw 2.2s ease-in-out infinite

  @keyframes draw
    0%
      stroke-dashoffset: 1

    40%
      stroke-dashoffset: 0

    60%
      stroke-dashoffset: 0

    100%
      stroke-dashoffset: 1
</style>
